ANDROID: 2024/04/24 KMI update
Increment KMI_GENERATION for the 2024/04/24 update.

1 variable symbol(s) removed
  'struct snd_soc_dai_link_component asoc_dummy_dlc'

6 function symbol(s) added
  'int __traceiter_android_rvh_set_gfp_zone_flags(void*, unsigned int*)'
  'int __traceiter_android_rvh_set_readahead_gfp_mask(void*, unsigned int*)'
  'int __traceiter_android_vh_binder_has_proc_work_ilocked(void*, struct binder_thread*, bool, bool*)'
  'int __traceiter_android_vh_binder_list_add_work(void*, struct binder_work*, struct list_head*)'
  'int __traceiter_android_vh_binder_release_special_work(void*, struct binder_proc*, struct list_head**)'
  'gfp_t readahead_gfp_mask(struct address_space*)'

6 variable symbol(s) added
  'struct tracepoint __tracepoint_android_rvh_set_gfp_zone_flags'
  'struct tracepoint __tracepoint_android_rvh_set_readahead_gfp_mask'
  'struct tracepoint __tracepoint_android_vh_binder_has_proc_work_ilocked'
  'struct tracepoint __tracepoint_android_vh_binder_list_add_work'
  'struct tracepoint __tracepoint_android_vh_binder_release_special_work'
  'struct snd_soc_dai_link_component snd_soc_dummy_dlc'

function symbol changed from 'int __traceiter_android_vh_map_util_freq(void*, unsigned long, unsigned long, unsigned long, unsigned long*)' to 'int __traceiter_android_vh_map_util_freq(void*, unsigned long, unsigned long, unsigned long, unsigned long*, struct cpufreq_policy*, bool*)'
  CRC changed from 0xf7d7ec49 to 0x4fdc2e4b
  type changed from 'int(void*, unsigned long, unsigned long, unsigned long, unsigned long*)' to 'int(void*, unsigned long, unsigned long, unsigned long, unsigned long*, struct cpufreq_policy*, bool*)'
    parameter 6 of type 'struct cpufreq_policy*' was added
    parameter 7 of type 'bool*' was added

variable symbol 'const struct dwc3* const ANDROID_GKI_struct_dwc3' changed
  CRC changed from 0x26933237 to 0x5913502b

function symbol 'struct block_device* I_BDEV(struct inode*)' changed
  CRC changed from 0x1f9a07a9 to 0xcd1f2630

function symbol 'void __ClearPageMovable(struct page*)' changed
  CRC changed from 0xcbb1eb20 to 0x2e2d7911

... 4434 omitted; 4437 symbols have only CRC changes

type 'struct request_queue' changed
  byte size changed from 1056 to 1072
  member 'struct throtl_data* td' was added
  11 members ('struct callback_head callback_head' .. 'bool mq_sysfs_init_done') changed
    offset changed by 64
  member 'u64 android_oem_data1' was added
  4 members ('u64 android_kabi_reserved1' .. 'u64 android_kabi_reserved4') changed
    offset changed by 128

type 'struct hci_dev' changed
  byte size changed from 6936 to 6944
  member 'struct sk_buff* req_rsp' was added
  86 members ('void* smp_data' .. 'u64 android_kabi_reserved4') changed
    offset changed by 64

type 'struct percpu_rw_semaphore' changed
  byte size changed from 96 to 104
  member 'u64 android_oem_data1' was added

type 'struct scsi_device' changed
  member 'unsigned int read_before_ms:1' was added
  35 members ('unsigned int no_report_opcodes:1' .. 'unsigned int cdl_enable:1') changed
    offset changed by 1

type 'struct binder_transaction' changed
  byte size changed from 184 to 192
  22 members ('struct binder_thread* from' .. 'u64 android_oem_data1') changed
    offset changed by 64

type 'struct binder_proc' changed
  byte size changed from 600 to 576
  5 members ('struct binder_context* context' .. 'bool oneway_spam_detection_enabled') changed
    offset changed by -192

type 'struct binder_thread' changed
  byte size changed from 448 to 464
  member 'struct binder_error reply_error' changed
    offset changed by 64
  9 members ('struct binder_extended_error ee' .. 'enum binder_prio_state prio_state') changed
    offset changed by 128

type 'struct binder_buffer' changed
  member changed from 'void* user_data' to 'unsigned long user_data'
    type changed from 'void*' to 'unsigned long'

type 'struct binder_work' changed
  byte size changed from 24 to 32
  member 'u64 android_oem_data1' was added

type 'struct ufs_hba' changed
  byte size changed from 5216 to 5232
  42 members ('bool auto_bkops_enabled' .. 'struct ufshcd_mcq_opr_info_t mcq_opr[4]') changed
    offset changed by 64
  member 'u64 android_oem_data1' was added

type 'struct super_block' changed
  27 members ('void* s_fs_info' .. 'int s_stack_depth') changed
    offset changed by 192

type 'struct kernfs_node' changed
  byte size changed from 136 to 152
  member 'struct callback_head rcu' was added
  member 'u64 android_kabi_reserved1' changed
    offset changed by 128

type 'struct per_cpu_pages' changed
  byte size changed from 256 to 320
  member changed from 'struct list_head lists[13]' to 'struct list_head lists[17]'
    type changed from 'struct list_head[13]' to 'struct list_head[17]'
      number of elements changed from 13 to 17

type 'struct binder_alloc' changed
  byte size changed from 144 to 120
  member 'struct mutex mutex' was removed
  member 'spinlock_t lock' was added
  2 members ('struct vm_area_struct* vma' .. 'struct mm_struct* mm') changed
    offset changed by -192
  member changed from 'void* buffer' to 'unsigned long buffer'
    offset changed from 384 to 192
    type changed from 'void*' to 'unsigned long'
  10 members ('struct list_head buffers' .. 'u64 android_oem_data1') changed
    offset changed by -192

type 'struct binder_error' changed
  byte size changed from 32 to 40
  member 'uint32_t cmd' changed
    offset changed by 64

type 'struct binder_node' changed
  byte size changed from 128 to 136
  13 members ('union { struct rb_node rb_node; struct hlist_node dead_node; }' .. 'struct list_head async_todo') changed
    offset changed by 64

type 'struct ufs_dev_info' changed
  byte size changed from 56 to 64
  member 'u64 android_oem_data1' was added
  2 members ('u64 android_kabi_reserved1' .. 'u64 android_kabi_reserved2') changed
    offset changed by 64

type 'struct sb_writers' changed
  byte size changed from 296 to 320

type 'struct io_ring_ctx' changed
  member 'struct socket* ring_sock' was removed
  18 members ('struct io_wq_hash* hash_map' .. 'struct page** sqe_pages') changed
    offset changed by -64

type 'struct kernfs_root' changed
  byte size changed from 240 to 256
  member 'struct callback_head rcu' was added

type 'struct kvm_hyp_iommu_domain' changed
  byte size changed from 24 to 32
  member changed from 'atomic_t refs' to 'unsigned int refs'
    type changed from 'atomic_t' = 'struct { int counter; }' to 'unsigned int'
      resolved type changed from 'struct { int counter; }' to 'unsigned int'
  member 'u32 unused' was added
INFO: Found 1 target...
Target //common:kernel_aarch64_abi_update up-to-date:
  bazel-bin/common/kernel_aarch64_abi_update.sh
INFO: Elapsed time: 288.498s, Critical Path: 282.22s
INFO: 17 processes: 1 internal, 14 linux-sandbox, 2 local.
INFO: Build completed successfully, 17 total actions
INFO: Running command line: bazel-bin/common/kernel_aarch64_abi_update.sh
ERROR: ABI DIFFERENCES HAVE BEEN DETECTED!
ERROR: 1 variable symbol(s) removed
  'struct snd_soc_dai_link_component asoc_dummy_dlc'

6 function symbol(s) added
  'int __traceiter_android_rvh_set_gfp_zone_flags(void*, unsigned int*)'
  'int __traceiter_android_rvh_set_readahead_gfp_mask(void*, unsigned int*)'
  'int __traceiter_android_vh_binder_has_proc_work_ilocked(void*, struct binder_thread*, bool, bool*)'
  'int __traceiter_android_vh_binder_list_add_work(void*, struct binder_work*, struct list_head*)'
  'int __traceiter_android_vh_binder_release_special_work(void*, struct binder_proc*, struct list_head**)'
  'gfp_t readahead_gfp_mask(struct address_space*)'

6 variable symbol(s) added
  'struct tracepoint __tracepoint_android_rvh_set_gfp_zone_flags'
  'struct tracepoint __tracepoint_android_rvh_set_readahead_gfp_mask'
  'struct tracepoint __tracepoint_android_vh_binder_has_proc_work_ilocked'
  'struct tracepoint __tracepoint_android_vh_binder_list_add_work'
  'struct tracepoint __tracepoint_android_vh_binder_release_special_work'
  'struct snd_soc_dai_link_component snd_soc_dummy_dlc'

function symbol changed from 'int __traceiter_android_vh_map_util_freq(void*, unsigned long, unsigned long, unsigned long, unsigned long*)' to 'int __traceiter_android_vh_map_util_freq(void*, unsigned long, unsigned long, unsigned long, unsigned long*, struct cpufreq_policy*, bool*)'
  CRC changed from 0xf7d7ec49 to 0x4fdc2e4b
  type changed from 'int(void*, unsigned long, unsigned long, unsigned long, unsigned long*)' to 'int(void*, unsigned long, unsigned long, unsigned long, unsigned long*, struct cpufreq_policy*, bool*)'
    parameter 6 of type 'struct cpufreq_policy*' was added
    parameter 7 of type 'bool*' was added

variable symbol 'const struct dwc3* const ANDROID_GKI_struct_dwc3' changed
  CRC changed from 0x26933237 to 0x5913502b

function symbol 'struct block_device* I_BDEV(struct inode*)' changed
  CRC changed from 0x1f9a07a9 to 0xcd1f2630

function symbol 'void __ClearPageMovable(struct page*)' changed
  CRC changed from 0xcbb1eb20 to 0x2e2d7911

... 4434 omitted; 4437 symbols have only CRC changes

type 'struct request_queue' changed
  byte size changed from 1056 to 1072
  member 'struct throtl_data* td' was added
  11 members ('struct callback_head callback_head' .. 'bool mq_sysfs_init_done') changed
    offset changed by 64
  member 'u64 android_oem_data1' was added
  4 members ('u64 android_kabi_reserved1' .. 'u64 android_kabi_reserved4') changed
    offset changed by 128

type 'struct hci_dev' changed
  byte size changed from 6936 to 6944
  member 'struct sk_buff* req_rsp' was added
  86 members ('void* smp_data' .. 'u64 android_kabi_reserved4') changed
    offset changed by 64

type 'struct percpu_rw_semaphore' changed
  byte size changed from 96 to 104
  member 'u64 android_oem_data1' was added

type 'struct scsi_device' changed
  member 'unsigned int read_before_ms:1' was added
  35 members ('unsigned int no_report_opcodes:1' .. 'unsigned int cdl_enable:1') changed
    offset changed by 1

type 'struct binder_transaction' changed
  byte size changed from 184 to 192
  22 members ('struct binder_thread* from' .. 'u64 android_oem_data1') changed
    offset changed by 64

type 'struct binder_proc' changed
  byte size changed from 600 to 576
  5 members ('struct binder_context* context' .. 'bool oneway_spam_detection_enabled') changed
    offset changed by -192

type 'struct binder_thread' changed
  byte size changed from 448 to 464
  member 'struct binder_error reply_error' changed
    offset changed by 64
  9 members ('struct binder_extended_error ee' .. 'enum binder_prio_state prio_state') changed
    offset changed by 128

type 'struct binder_buffer' changed
  member changed from 'void* user_data' to 'unsigned long user_data'
    type changed from 'void*' to 'unsigned long'

type 'struct binder_work' changed
  byte size changed from 24 to 32
  member 'u64 android_oem_data1' was added

type 'struct ufs_hba' changed
  byte size changed from 5216 to 5232
  42 members ('bool auto_bkops_enabled' .. 'struct ufshcd_mcq_opr_info_t mcq_opr[4]') changed
    offset changed by 64
  member 'u64 android_oem_data1' was added

type 'struct super_block' changed
  27 members ('void* s_fs_info' .. 'int s_stack_depth') changed
    offset changed by 192

type 'struct kernfs_node' changed
  byte size changed from 136 to 152
  member 'struct callback_head rcu' was added
  member 'u64 android_kabi_reserved1' changed
    offset changed by 128

type 'struct per_cpu_pages' changed
  byte size changed from 256 to 320
  member changed from 'struct list_head lists[13]' to 'struct list_head lists[17]'
    type changed from 'struct list_head[13]' to 'struct list_head[17]'
      number of elements changed from 13 to 17

type 'struct binder_alloc' changed
  byte size changed from 144 to 120
  member 'struct mutex mutex' was removed
  member 'spinlock_t lock' was added
  2 members ('struct vm_area_struct* vma' .. 'struct mm_struct* mm') changed
    offset changed by -192
  member changed from 'void* buffer' to 'unsigned long buffer'
    offset changed from 384 to 192
    type changed from 'void*' to 'unsigned long'
  10 members ('struct list_head buffers' .. 'u64 android_oem_data1') changed
    offset changed by -192

type 'struct binder_error' changed
  byte size changed from 32 to 40
  member 'uint32_t cmd' changed
    offset changed by 64

type 'struct binder_node' changed
  byte size changed from 128 to 136
  13 members ('union { struct rb_node rb_node; struct hlist_node dead_node; }' .. 'struct list_head async_todo') changed
    offset changed by 64

type 'struct ufs_dev_info' changed
  byte size changed from 56 to 64
  member 'u64 android_oem_data1' was added
  2 members ('u64 android_kabi_reserved1' .. 'u64 android_kabi_reserved2') changed
    offset changed by 64

type 'struct sb_writers' changed
  byte size changed from 296 to 320

type 'struct io_ring_ctx' changed
  member 'struct socket* ring_sock' was removed
  18 members ('struct io_wq_hash* hash_map' .. 'struct page** sqe_pages') changed
    offset changed by -64

type 'struct kernfs_root' changed
  byte size changed from 240 to 256
  member 'struct callback_head rcu' was added

type 'struct kvm_hyp_iommu_domain' changed
  byte size changed from 24 to 32
  member changed from 'atomic_t refs' to 'unsigned int refs'
    type changed from 'atomic_t' = 'struct { int counter; }' to 'unsigned int'
      resolved type changed from 'struct { int counter; }' to 'unsigned int'
  member 'u32 unused' was added

Bug: 336873268
Change-Id: Idd25b5b585aaee899c802efef5c64b368cac6090
Signed-off-by: Carlos Llamas <cmllamas@google.com>