ANDROID: mm: fix previous commit in alloc_contig_range
There were mistake in declaration of vendor hook in previous commit
https://android-review.googlesource.com/c/kernel/common/+/3164023.

- TP_PROTO(unsigned long start, unsigned end),
+ TP_PROTO(unsigned long start, unsigned long end),

ERROR: function symbol changed from 'int __traceiter_android_vh_alloc_contig_range_not_isolated(void*, unsigned long, unsigned int)' to 'int __traceiter_android_vh_alloc_contig_range_not_isolated(void*, unsigned long, unsigned long)'
  CRC changed from 0xaccb4007 to 0x5ff5e446
  type changed from 'int(void*, unsigned long, unsigned int)' to 'int(void*, unsigned long, unsigned long)'
    parameter 3 type changed from 'unsigned int' to 'unsigned long'

Bug: 351175506
Change-Id: I96ef5e16cc1b875b442fba43d83a169c6a9738ba
Signed-off-by: Sooyong Suk <s.suk@samsung.corp-partner.google.com>