ANDROID: kleaf: Expect new kernel module phy-qcom-qmp-usbc.ko
Commit 19281571a4d5 ("phy: qcom: qmp-usb: split USB-C PHY driver")
pulled USB-C handing out from phy-qcom-qmp-usb.ko and into a new kernel
module phy-qcom-qmp-usbc.ko.  Let's tell Bazel about it.

Fixes the following pre-submit error message:

  ERROR: The following kernel modules are built but not copied.
    Add these lines to the module_outs attribute of @@//common:db845c_no_kgdb:
      "drivers/phy/qualcomm/phy-qcom-qmp-usbc.ko",

Fixes: 19281571a4d5 ("phy: qcom: qmp-usb: split USB-C PHY driver")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: I367b56418767f74fe0e0f5eec3a3ac901da0296d