ANDROID: GKI: x86: Add NFS_FS to GKI modules
NFS_FS as vendor modules is problematic because of the following
dependency chain:
NET_HANDSHAKE=y depends on -> SUNRPC=m which has to be
selected by -> NFS_FS=m
which results in build error:
sunrpc.ko is missing tls_client_hello_anon() symbol:
ERROR: modpost: "tls_client_hello_anon" [net/sunrpc/sunrpc.ko] undefined!

In order to have tls_client_hello_anon() exported NET_HANDSHAKE=y is
needed in gki_defconfig but SUNRPC=m is currently vendor module.

Furthermore, current Kconfig does not assume SUNRPC=m to be
a standalone module. So the implication of NFS_FS=m is having
an extra SUNRPC=m module which together with NET_HANDSHAKE=y
is 2-way dependency.

The workable solution for now is to have NFS_FS=m as GKI module...

Bug: 355688481
Test: Build GKI and check if there is no build errors

Change-Id: Ib067e8d49c99cdf062b932cd632cd2d71227ddc5
Signed-off-by: Tomasz Nowicki <tnowicki@google.com>
Signed-off-by: Slawomir Rosek <srosek@google.com>